import Alignment.FiniteIndependentAlignmentDecision
import StrongPerimetralTurning

/-!
# History-derived constitutive alignment

This module removes an independently supplied local relation from the canonical
history-based alignment path.

For a proof-relevant finite history, the identity carrier is its occurrence
type. Structural precedence is already generated by the constructors of
`History.OccurrencePrecedes`. We expose a computable local observation of that
precedence, prove that its complete self-profile separates occurrences, derive a
complete finite occurrence listing, and invoke the independent-observation
alignment decision.

The public history decision therefore takes only two finite constitutive
histories. No relation, relation-value carrier, anchor, mediator, transport, or
carrier listing is supplied by the caller.
-/

namespace Alignment
namespace GenesisReconstruction
namespace HistoryDerivedAlignment

open StrongPerimetralTurning
open FiniteAnchoredMatchSearch
open FiniteIntrinsicFunctionEnumeration

universe uState uStep uCarrier

/--
A local chronology observation. The phantom carrier parameter keeps observations
local to the occurrence carrier that generated them.
-/
structure LocalChronologyObservation (Carrier : Type uCarrier) where
  precedes : Bool
deriving DecidableEq

/-- Computable strict precedence generated solely from occurrence constructors. -/
def occurrencePrecedesBool
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    {history : History Step source target} :
    History.Occurrence history →
      History.Occurrence history →
      Bool
  | .last, _ => false
  | .earlier _, .last => true
  | .earlier first, .earlier second =>
      occurrencePrecedesBool first second

/-- No occurrence structurally precedes itself. -/
theorem occurrencePrecedesBool_self
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    {history : History Step source target}
    (occurrence : History.Occurrence history) :
    occurrencePrecedesBool occurrence occurrence = false := by
  induction occurrence with
  | last =>
      rfl
  | earlier occurrence inductionHypothesis =>
      exact inductionHypothesis

/-- Proof-relevant precedence computes to the positive local observation. -/
theorem occurrencePrecedesBool_true_of_precedes
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    {history : History Step source target}
    {first second : History.Occurrence history}
    (precedes : History.OccurrencePrecedes first second) :
    occurrencePrecedesBool first second = true := by
  induction precedes with
  | earlier_last =>
      rfl
  | earlier_earlier _ inductionHypothesis =>
      exact inductionHypothesis

/-- Positive computation reconstructs the proof-relevant precedence relation. -/
theorem occurrencePrecedes_of_bool_true
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    {history : History Step source target}
    (first second : History.Occurrence history)
    (checked : occurrencePrecedesBool first second = true) :
    History.OccurrencePrecedes first second := by
  induction first with
  | last =>
      cases second <;> cases checked
  | earlier first inductionHypothesis =>
      cases second with
      | last =>
          exact .earlier_last first
      | earlier second =>
          exact .earlier_earlier (inductionHypothesis second checked)

/--
The local relation is not input data: it is the Boolean image of the
proof-relevant structural precedence generated by the history itself.
-/
def historyRelation
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    {history : History Step source target}
    (first second : History.Occurrence history) :
    LocalChronologyObservation (History.Occurrence history) :=
  ⟨occurrencePrecedesBool first second⟩

/-- The derived relation is extensionally equivalent to proof-relevant precedence. -/
theorem historyRelation_precedes_iff
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    {history : History Step source target}
    (first second : History.Occurrence history) :
    (historyRelation first second).precedes = true ↔
      History.OccurrencePrecedes first second := by
  constructor
  · intro checked
    exact occurrencePrecedes_of_bool_true first second checked
  · intro precedes
    exact occurrencePrecedesBool_true_of_precedes precedes

/--
Structural chronology separates occurrences: if every possible predecessor
sees two identities identically, the identities are equal.
-/
theorem historyRelation_separates
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    {history : History Step source target} :
    ProfileSeparates
      (fun identity anchor : History.Occurrence history =>
        historyRelation anchor identity) := by
  intro first second agreement
  rcases History.OccurrencePrecedes.trichotomy first second with
    equality | firstBeforeSecond | secondBeforeFirst
  · exact equality
  · have observed := agreement first
    have booleanEquality :=
      congrArg LocalChronologyObservation.precedes observed
    change
      occurrencePrecedesBool first first =
        occurrencePrecedesBool first second at booleanEquality
    rw [occurrencePrecedesBool_self,
      occurrencePrecedesBool_true_of_precedes firstBeforeSecond]
      at booleanEquality
    cases booleanEquality
  · have observed := agreement second
    have booleanEquality :=
      congrArg LocalChronologyObservation.precedes observed
    change
      occurrencePrecedesBool second first =
        occurrencePrecedesBool second second at booleanEquality
    rw [occurrencePrecedesBool_true_of_precedes secondBeforeFirst,
      occurrencePrecedesBool_self]
      at booleanEquality
    cases booleanEquality

/-- Structural age: distance in constructors from the latest occurrence. -/
def occurrenceAge
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    {history : History Step source target} :
    History.Occurrence history → Nat
  | .last => 0
  | .earlier previous => occurrenceAge previous + 1

/-- Earlier occurrences have strictly greater structural age. -/
theorem occurrenceAge_gt_of_precedes
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    {history : History Step source target}
    {first second : History.Occurrence history}
    (precedes : History.OccurrencePrecedes first second) :
    occurrenceAge second < occurrenceAge first := by
  induction precedes with
  | earlier_last occurrence =>
      change 0 < occurrenceAge occurrence + 1
      exact Nat.zero_lt_succ _
  | earlier_earlier _ inductionHypothesis =>
      change
        occurrenceAge _ + 1 < occurrenceAge _ + 1
      exact Nat.succ_lt_succ inductionHypothesis

/-- Structural age is a complete identity code inside one finite history. -/
theorem occurrenceAge_injective
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    {history : History Step source target} :
    Function.Injective
      (@occurrenceAge State Step source target history) := by
  intro first second ageEquality
  rcases History.OccurrencePrecedes.trichotomy first second with
    equality | firstBeforeSecond | secondBeforeFirst
  · exact equality
  · have strict := occurrenceAge_gt_of_precedes firstBeforeSecond
    rw [ageEquality] at strict
    exact False.elim (Nat.lt_irrefl _ strict)
  · have strict := occurrenceAge_gt_of_precedes secondBeforeFirst
    rw [ageEquality] at strict
    exact False.elim (Nat.lt_irrefl _ strict)

/--
Constructive decidable equality of occurrences through the internally derived
structural age. Only decidable equality of natural numbers is executed.
-/
def occurrenceDecidableEq
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    (history : History Step source target) :
    DecidableEq (History.Occurrence history) :=
  fun first second =>
    match Nat.decEq (occurrenceAge first) (occurrenceAge second) with
    | isTrue equality =>
        isTrue (occurrenceAge_injective equality)
    | isFalse distinct =>
        isFalse
          (fun equality =>
            distinct (congrArg occurrenceAge equality))

/-- Every occurrence age is strictly below the derived history length. -/
theorem occurrenceAge_lt_length
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    {history : History Step source target}
    (occurrence : History.Occurrence history) :
    occurrenceAge occurrence < History.length history := by
  induction occurrence with
  | last =>
      exact Nat.zero_lt_succ _
  | earlier occurrence inductionHypothesis =>
      change occurrenceAge occurrence + 1 < History.length _ + 1
      exact Nat.succ_lt_succ inductionHypothesis

/-- Canonical finite structural index of one occurrence. -/
def occurrenceFin
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    {history : History Step source target}
    (occurrence : History.Occurrence history) :
    Fin (History.length history) :=
  ⟨occurrenceAge occurrence, occurrenceAge_lt_length occurrence⟩

/-- Constructive enumeration of every element of `Fin n`. -/
def finValues : (n : Nat) → List (Fin n)
  | 0 => []
  | n + 1 =>
      ⟨0, Nat.zero_lt_succ n⟩ ::
        (finValues n).map Fin.succ

/-- The constructive finite-index enumeration is complete. -/
theorem finValues_complete
    (n : Nat)
    (index : Fin n) :
    index ∈ finValues n := by
  induction n with
  | zero =>
      exact Fin.elim0 index
  | succ n inductionHypothesis =>
      cases index with
      | mk value bound =>
          cases value with
          | zero =>
              exact List.Mem.head _
          | succ value =>
              have priorBound : value < n :=
                Nat.lt_of_succ_lt_succ bound
              have priorMember :
                  (⟨value, priorBound⟩ : Fin n) ∈ finValues n :=
                inductionHypothesis ⟨value, priorBound⟩
              exact
                List.Mem.tail _
                  (mem_map_of_mem Fin.succ priorMember)

/--
Reconstruct the occurrence at a supplied structural age index. This is a
positive recursive construction from the finite history itself.
-/
def occurrenceAtFin
    {State : Type uState}
    {Step : State → State → Type uStep} :
    {source target : State} →
      (history : History Step source target) →
      Fin (History.length history) →
      History.Occurrence history
  | _, _, .root, index =>
      Fin.elim0 index
  | _, _, .extend previous step, ⟨0, _⟩ =>
      .last
  | _, _, .extend previous step, ⟨value + 1, bound⟩ =>
      .earlier
        (occurrenceAtFin previous
          ⟨value, Nat.lt_of_succ_lt_succ bound⟩)

/-- Reconstruction at an index has exactly that structural age. -/
theorem occurrenceAtFin_age
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    (history : History Step source target)
    (index : Fin (History.length history)) :
    occurrenceAge (occurrenceAtFin history index) = index.val := by
  induction history with
  | root =>
      exact Fin.elim0 index
  | @extend source middle target previous step inductionHypothesis =>
      cases index with
      | mk value bound =>
          cases value with
          | zero =>
              rfl
          | succ value =>
              change
                occurrenceAge
                    (occurrenceAtFin previous
                      ⟨value, Nat.lt_of_succ_lt_succ bound⟩) + 1 =
                  value + 1
              exact
                congrArg
                  (fun current => current + 1)
                  (inductionHypothesis
                    ⟨value, Nat.lt_of_succ_lt_succ bound⟩)

/-- Finite structural indexing reconstructs every occurrence exactly. -/
theorem occurrenceAtFin_occurrenceFin
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    {history : History Step source target}
    (occurrence : History.Occurrence history) :
    occurrenceAtFin history (occurrenceFin occurrence) = occurrence := by
  apply occurrenceAge_injective
  exact occurrenceAtFin_age history (occurrenceFin occurrence)

/-- Raw finite occurrence enumeration via the derived structural indices. -/
def occurrenceValues
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    (history : History Step source target) :
    List (History.Occurrence history) :=
  (finValues (History.length history)).map
    (occurrenceAtFin history)

/-- Every occurrence appears in the structurally derived finite enumeration. -/
theorem occurrence_mem_values
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    {history : History Step source target}
    (occurrence : History.Occurrence history) :
    occurrence ∈ occurrenceValues history := by
  have indexMember :
      occurrenceFin occurrence ∈ finValues (History.length history) :=
    finValues_complete _ (occurrenceFin occurrence)
  have mapped :
      occurrenceAtFin history (occurrenceFin occurrence) ∈
        occurrenceValues history := by
    unfold occurrenceValues
    exact mem_map_of_mem (occurrenceAtFin history) indexMember
  rw [occurrenceAtFin_occurrenceFin occurrence] at mapped
  exact mapped

/-- Complete finite listing derived from the history, with no supplied carrier list. -/
def occurrenceListing
    {State : Type uState}
    {Step : State → State → Type uStep}
    {source target : State}
    (history : History Step source target) :
    FiniteListing (History.Occurrence history) :=
  { values := occurrenceValues history
    complete := occurrence_mem_values }

/--
The complete independent relational context derived from two histories.
Nothing relational is supplied independently of those histories.
-/
def context
    {SourceState : Type uState}
    {SourceStep : SourceState → SourceState → Type uStep}
    {sourceStart sourceEnd : SourceState}
    (sourceHistory : History SourceStep sourceStart sourceEnd)
    {TargetState : Type uCarrier}
    {TargetStep : TargetState → TargetState → Type uStep}
    {targetStart targetEnd : TargetState}
    (targetHistory : History TargetStep targetStart targetEnd) :
    IndependentRelationalContext
      (History.Occurrence sourceHistory)
      (History.Occurrence targetHistory)
      (LocalChronologyObservation (History.Occurrence sourceHistory))
      (LocalChronologyObservation (History.Occurrence targetHistory)) :=
  { sourceRelation := historyRelation
    targetRelation := historyRelation
    sourceSeparates := historyRelation_separates
    targetSeparates := historyRelation_separates }

/-- Closed constitutive alignment type derived from the two histories alone. -/
abbrev ConstitutiveAlignment
    {SourceState : Type uState}
    {SourceStep : SourceState → SourceState → Type uStep}
    {sourceStart sourceEnd : SourceState}
    (sourceHistory : History SourceStep sourceStart sourceEnd)
    {TargetState : Type uCarrier}
    {TargetStep : TargetState → TargetState → Type uStep}
    {targetStart targetEnd : TargetState}
    (targetHistory : History TargetStep targetStart targetEnd) : Type _ :=
  IndependentConstitutiveAlignment (context sourceHistory targetHistory)

/--
End-to-end constructive decision from two finite constitutive histories alone.
-/
def decide
    {SourceState : Type uState}
    {SourceStep : SourceState → SourceState → Type uStep}
    {sourceStart sourceEnd : SourceState}
    (sourceHistory : History SourceStep sourceStart sourceEnd)
    {TargetState : Type uCarrier}
    {TargetStep : TargetState → TargetState → Type uStep}
    {targetStart targetEnd : TargetState}
    (targetHistory : History TargetStep targetStart targetEnd) :
    FiniteIndependentAlignmentDecision.AlignmentDecision
      (context sourceHistory targetHistory) := by
  letI : DecidableEq (History.Occurrence sourceHistory) :=
    occurrenceDecidableEq sourceHistory
  letI : DecidableEq (History.Occurrence targetHistory) :=
    occurrenceDecidableEq targetHistory
  exact
    FiniteIndependentAlignmentDecision.decideAlignmentFromListings
      (context sourceHistory targetHistory)
      (occurrenceListing sourceHistory)
      (occurrenceListing targetHistory)

end HistoryDerivedAlignment
end GenesisReconstruction
end Alignment

/- AXIOM_AUDIT_BEGIN -/
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.LocalChronologyObservation
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrencePrecedesBool
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrencePrecedesBool_self
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrencePrecedesBool_true_of_precedes
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrencePrecedes_of_bool_true
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.historyRelation
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.historyRelation_precedes_iff
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.historyRelation_separates
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrenceAge
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrenceAge_gt_of_precedes
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrenceAge_injective
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrenceDecidableEq
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrenceAge_lt_length
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrenceFin
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.finValues
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.finValues_complete
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrenceAtFin
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrenceAtFin_age
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrenceAtFin_occurrenceFin
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrenceValues
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrence_mem_values
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.occurrenceListing
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.context
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.ConstitutiveAlignment
#print axioms Alignment.GenesisReconstruction.HistoryDerivedAlignment.decide
/- AXIOM_AUDIT_END -/
