import ConstitutiveAlignment.Machine
import ConstitutiveAlignment.CausalMemory
import ConstitutiveAlignment.NormativeExecution
import ConstitutiveAlignment.NormativeFailure
import ConstitutiveAlignment.Succession
import ConstitutiveAlignment.LearningCausality
import ConstitutiveAlignment.ReflectiveMachine
import ConstitutiveAlignment.ReferenceModel
import ConstitutiveAlignment.NeuralRealization
import ConstitutiveAlignment.TransformerDynamics
import ConstitutiveAlignment.FreshProbeCausality
import ConstitutiveAlignment.GovernedDynamics
import ConstitutiveAlignment.ExecutableRefinement
import ConstitutiveAlignment.TypedProgramDomain
import ConstitutiveAlignment.EndogenousTypedSuccession
import ConstitutiveAlignment.VerificationTransport

/-!
# Constitutive alignment architecture

This facade exports only modules that have passed their constructive build and
dependency audits.  Further layers are added in dependency order.
-/

/- AXIOM_AUDIT_BEGIN -/
#print axioms ConstitutiveAlignment.oneStepNormativeFailure
#print axioms ConstitutiveAlignment.MemoryExamples.richMemoryExact
#print axioms ConstitutiveAlignment.MemoryExamples.richMemoryUpdate
#print axioms ConstitutiveAlignment.CertifiedEffectuation.normative
#print axioms ConstitutiveAlignment.SuccessionExamples.twoLinkedToggles
#print axioms ConstitutiveAlignment.SuccessionExamples.explicitStop
#print axioms ConstitutiveAlignment.LearningExamples.causalWitness
#print axioms ConstitutiveAlignment.exactMachineStatusRepresentation_hasDiagonalOutside
#print axioms ConstitutiveAlignment.ReferenceModel.architectureCertificate
#print axioms ConstitutiveAlignment.ReferenceModel.secondCycle_consumesReconfiguredMemory
#print axioms ConstitutiveAlignment.NeuralExamples.intervention
#print axioms ConstitutiveAlignment.TransformerExamples.oneStepIntervention
#print axioms ConstitutiveAlignment.TransformerExamples.causalSuccession
#print axioms ConstitutiveAlignment.TransformerExamples.proposedRelationConsumption
#print axioms ConstitutiveAlignment.TransformerExamples.finiteGateICertificate
#print axioms ConstitutiveAlignment.TransformerExamples.predictionInvariant_underAddressRenaming
#print axioms ConstitutiveAlignment.TransformerExamples.acceptedLearnedProposal_isPreserved
#print axioms ConstitutiveAlignment.TransformerDynamics.twoLinkedTransformerCycles
#print axioms ConstitutiveAlignment.TransformerDynamics.intercycleAblation_changesSecondProposal
#print axioms ConstitutiveAlignment.TransformerDynamics.finiteGateJCertificate
#print axioms ConstitutiveAlignment.FreshProbeExamples.strictFreshProbeGateCertificate
#print axioms ConstitutiveAlignment.TransformerGovernedDynamics.invariantAt
#print axioms ConstitutiveAlignment.TransformerGovernedDynamics.proposalIsNextConsumedRelation
#print axioms ConstitutiveAlignment.TransformerGovernedDynamics.relationAblation_changesPredictionAtEveryDepth
#print axioms ConstitutiveAlignment.TransformerGovernedDynamics.gateLCertificate
#print axioms ConstitutiveAlignment.ExecutableRefinement.refinementAt
#print axioms ConstitutiveAlignment.ExecutableRefinement.nextExecutableConsumesPreviousProposal
#print axioms ConstitutiveAlignment.ExecutableRefinement.rewrittenParentCandidate_hasNoRefinement
#print axioms ConstitutiveAlignment.ExecutableRefinement.forgedParentEffect_hasNoRefinement
#print axioms ConstitutiveAlignment.ExecutableRefinement.gateMCertificate
#print axioms ConstitutiveAlignment.TypedProgram.programAdequacy
#print axioms ConstitutiveAlignment.TypedProgram.firstFrontier_isDoubleNegate
#print axioms ConstitutiveAlignment.TypedProgram.secondFrontier_isTripleNegate
#print axioms ConstitutiveAlignment.EndogenousTypedSuccession.firstStep_reconstructsCorpus
#print axioms ConstitutiveAlignment.EndogenousTypedSuccession.secondStep_consumesFirstSuccessor
#print axioms ConstitutiveAlignment.EndogenousTypedSuccession.strictGeneratedCausality
#print axioms ConstitutiveAlignment.EndogenousTypedSuccession.compactTypedSelfExtension
#print axioms ConstitutiveAlignment.FaithfulRun.sourceToPresented
#print axioms ConstitutiveAlignment.transportNoCounterexample
#print axioms ConstitutiveAlignment.SemanticChecker.SoundnessFactorization.sound
#print axioms ConstitutiveAlignment.ConstitutivelySoundRun.semantic
#print axioms ConstitutiveAlignment.NoFalseSemanticSlice.excludesFalse
#print axioms ConstitutiveAlignment.ConstructiveEmptyFoundation.derivedEmpty
#print axioms ConstitutiveAlignment.shadowExtract
#print axioms ConstitutiveAlignment.historicalStable_implies_weaklyStable
#print axioms ConstitutiveAlignment.separator_refutes_localReconstruction
#print axioms ConstitutiveAlignment.separator_refutes_historicalStability
#print axioms ConstitutiveAlignment.VerificationSeparators.acceptedPresentation_doesNotDetermineOrigin
#print axioms ConstitutiveAlignment.VerificationSeparators.NoFalseSlice.inhabitation_isNecessary
#print axioms ConstitutiveAlignment.VerificationSeparators.NoFalseSlice.falseTypeReading_isNecessary
#print axioms ConstitutiveAlignment.VerificationSeparators.NoFalseSlice.emptyExclusion_isNecessary
#print axioms ConstitutiveAlignment.VerificationSeparators.NoFalseSlice.totalMembership_hasNoEmptyWitness
#print axioms ConstitutiveAlignment.VerificationSeparators.InternalAlignment.unsoundChecker_hasNoSoundness
#print axioms ConstitutiveAlignment.VerificationSeparators.InternalAlignment.selectiveChecker_hasNoCompleteness
#print axioms ConstitutiveAlignment.VerificationSeparators.InternalAlignment.soundAcceptanceAndSemantics_doNotDetermineOrigin
#print axioms ConstitutiveAlignment.ConLecheProjectionCase.projectionNoFalseTransport
#print axioms ConstitutiveAlignment.ConLecheProjectionCase.metadataErasureNoFalseTransport
#print axioms ConstitutiveAlignment.ConLecheProjectionCase.acceptedSubstitution_hasNoFaithfulRewrite
/- AXIOM_AUDIT_END -/
