import ConstitutiveSearch.ClosureSearchFixedFuelPolynomial

/-!
# Growing-fuel separator for closure search

The fixed-fuel theory proves polynomiality for every fuel value chosen
independently of the input.  This module records a concrete boundary case where
the fuel itself is the input-size index.

With one explicit intermediate candidate, both closure counters reduce to the
same binary recurrence.  We expose that recurrence as an exact doubling scale
and combine it with the already-proved exact polynomial-degree theorem.

This is a structural growth separator for the announced ClosureSearch engine.
It does not by itself assert a machine-time lower bound or a general
non-polynomiality theorem.
-/

namespace ConstitutiveSearch

/--
Canonical doubling scale generated by the fuel:
S(0) = 1 and S(f+1) = S(f) + S(f).
-/
def binaryFuelScale : Nat → Nat
  | 0 => 1
  | fuel + 1 =>
      binaryFuelScale fuel +
        binaryFuelScale fuel

/-- The internal doubling scale is exactly the natural power 2^fuel. -/
theorem binaryFuelScale_eq_two_pow :
    ∀ fuel : Nat,
      binaryFuelScale fuel =
        2 ^ fuel := by
  intro fuel
  induction fuel with
  | zero =>
      rfl
  | succ fuel inductionHypothesis =>
      change
        binaryFuelScale fuel +
            binaryFuelScale fuel =
          2 ^ (fuel + 1)
      rw [
        inductionHypothesis,
        Nat.pow_add_one,
        Nat.mul_two
      ]

/--
The one-candidate closure budget is exactly one below the doubling scale.
Writing the identity without subtraction keeps it purely in Nat arithmetic.
-/
theorem binaryClosureBudget_add_one_eq_binaryFuelScale :
    ∀ fuel : Nat,
      binaryClosureBudget fuel + 1 =
        binaryFuelScale fuel := by
  intro fuel
  induction fuel with
  | zero =>
      rfl
  | succ fuel inductionHypothesis =>
      change
        (binaryClosureBudget fuel +
              binaryClosureBudget fuel +
            1) +
          1 =
        binaryFuelScale fuel +
          binaryFuelScale fuel
      calc
        (binaryClosureBudget fuel +
              binaryClosureBudget fuel +
            1) +
          1
            =
          (binaryClosureBudget fuel + 1) +
            (binaryClosureBudget fuel + 1) :=
          Constructive.nat_double_add_two
            (binaryClosureBudget fuel)
        _ =
          binaryFuelScale fuel +
            binaryFuelScale fuel :=
          Eq.trans
            (congrArg
              (fun value =>
                value +
                  (binaryClosureBudget fuel + 1))
              inductionHypothesis)
            (congrArg
              (Nat.add (binaryFuelScale fuel))
              inductionHypothesis)

/--
If fuel equals the input-size index and there is one candidate, primitive-query
budget follows the exact doubling scale.
-/
theorem closurePrimitiveOneCandidateGrowingFuel_exact
    (inputBits : Nat) :
    closurePrimitiveQueryBudget 1 inputBits + 1 =
      binaryFuelScale inputBits := by
  rw [closurePrimitiveQueryBudget_one_eq_binary]
  exact
    binaryClosureBudget_add_one_eq_binaryFuelScale
      inputBits

/-- Closed form: one-candidate primitive-query budget plus one is 2^inputBits. -/
theorem closurePrimitiveOneCandidateGrowingFuel_eq_two_pow
    (inputBits : Nat) :
    closurePrimitiveQueryBudget 1 inputBits + 1 =
      2 ^ inputBits :=
  Eq.trans
    (closurePrimitiveOneCandidateGrowingFuel_exact
      inputBits)
    (binaryFuelScale_eq_two_pow inputBits)

/--
The composition-candidate budget has the same exact growing-fuel behavior.
-/
theorem closureCompositionOneCandidateGrowingFuel_exact
    (inputBits : Nat) :
    closureCompositionCandidateBudget 1 inputBits + 1 =
      binaryFuelScale inputBits := by
  rw [closureCompositionCandidateBudget_one_eq_binary]
  exact
    binaryClosureBudget_add_one_eq_binaryFuelScale
      inputBits

/-- Closed form: one-candidate composition budget plus one is 2^inputBits. -/
theorem closureCompositionOneCandidateGrowingFuel_eq_two_pow
    (inputBits : Nat) :
    closureCompositionCandidateBudget 1 inputBits + 1 =
      2 ^ inputBits :=
  Eq.trans
    (closureCompositionOneCandidateGrowingFuel_exact
      inputBits)
    (binaryFuelScale_eq_two_pow inputBits)

/-- Identity fuel is unbounded. -/
theorem identityFuel_unbounded :
    ∀ cap : Nat,
      ∃ inputBits : Nat,
        cap < inputBits := by
  intro cap
  exact
    ⟨cap + 1,
      Nat.lt_succ_self cap⟩

/--
For fuel(inputBits) = inputBits, exact primitive-query polynomials have
unbounded structural degree.
-/
theorem closurePrimitiveIdentityFuel_degree_unbounded :
    ∀ degreeCap : Nat,
      ∃ inputBits : Nat,
        degreeCap <
          (closurePrimitiveFixedFuelPolynomial
            inputBits).degree :=
  closurePrimitiveFixedFuelPolynomial_degree_unbounded
    (fun inputBits => inputBits)
    identityFuel_unbounded

/--
The exact composition-candidate polynomial degrees are likewise unbounded.
-/
theorem closureCompositionIdentityFuel_degree_unbounded :
    ∀ degreeCap : Nat,
      ∃ inputBits : Nat,
        degreeCap <
          (closureCompositionFixedFuelPolynomial
            inputBits).degree :=
  closureCompositionFixedFuelPolynomial_degree_unbounded
    (fun inputBits => inputBits)
    identityFuel_unbounded

/--
Hence there is no one uniform degree cap for the canonical exact
primitive-query polynomial family when fuel(inputBits) = inputBits.
-/
theorem closurePrimitiveIdentityFuel_no_uniform_degree :
    ¬
      ∃ degreeCap : Nat,
        ∀ inputBits : Nat,
          (closurePrimitiveFixedFuelPolynomial
            inputBits).degree ≤ degreeCap := by
  intro bounded
  rcases bounded with
    ⟨degreeCap, degreeLe⟩
  rcases
      closurePrimitiveIdentityFuel_degree_unbounded
        degreeCap with
    ⟨inputBits, degreeLt⟩
  have impossible :
      degreeCap < degreeCap :=
    Nat.lt_of_lt_of_le
      degreeLt
      (degreeLe inputBits)
  exact
    (Nat.lt_irrefl degreeCap)
      impossible

/--
The same no-uniform-degree separator holds for composition-candidate
polynomials.
-/
theorem closureCompositionIdentityFuel_no_uniform_degree :
    ¬
      ∃ degreeCap : Nat,
        ∀ inputBits : Nat,
          (closureCompositionFixedFuelPolynomial
            inputBits).degree ≤ degreeCap := by
  intro bounded
  rcases bounded with
    ⟨degreeCap, degreeLe⟩
  rcases
      closureCompositionIdentityFuel_degree_unbounded
        degreeCap with
    ⟨inputBits, degreeLt⟩
  have impossible :
      degreeCap < degreeCap :=
    Nat.lt_of_lt_of_le
      degreeLt
      (degreeLe inputBits)
  exact
    (Nat.lt_irrefl degreeCap)
      impossible

end ConstitutiveSearch

/- AXIOM_AUDIT_BEGIN -/
#print axioms ConstitutiveSearch.binaryFuelScale
#print axioms ConstitutiveSearch.binaryFuelScale_eq_two_pow
#print axioms ConstitutiveSearch.binaryClosureBudget_add_one_eq_binaryFuelScale
#print axioms ConstitutiveSearch.closurePrimitiveOneCandidateGrowingFuel_exact
#print axioms ConstitutiveSearch.closurePrimitiveOneCandidateGrowingFuel_eq_two_pow
#print axioms ConstitutiveSearch.closureCompositionOneCandidateGrowingFuel_exact
#print axioms ConstitutiveSearch.closureCompositionOneCandidateGrowingFuel_eq_two_pow
#print axioms ConstitutiveSearch.identityFuel_unbounded
#print axioms ConstitutiveSearch.closurePrimitiveIdentityFuel_degree_unbounded
#print axioms ConstitutiveSearch.closureCompositionIdentityFuel_degree_unbounded
#print axioms ConstitutiveSearch.closurePrimitiveIdentityFuel_no_uniform_degree
#print axioms ConstitutiveSearch.closureCompositionIdentityFuel_no_uniform_degree
/- AXIOM_AUDIT_END -/
