import Alignment.HistoryDerivedRigidity
import StrongPerimetralTurning.IteratedConstitutivePersistence

open Alignment

/-!
# History-derived intrinsic alignment in the circular realization

This module connects the relation-free history-derived alignment layer to the
actual circular constitutive producer and its concrete realizations.

The exact interpretation of a generated history preserves the chronology
generated by occurrence constructors. Hence the already existing
concrete-to-concrete transport is a history-derived intrinsic alignment. Since
history chronology is pattern-rigid, any other compatible intrinsic alignment
must agree with that transport pointwise.
-/

namespace StrongPerimetralTurning
namespace HistoryDerivedIntrinsicAlignment

open Alignment.GenesisReconstruction
open Alignment.GenesisReconstruction.HistoryDerivedAlignment
open StrongPerimetralTurning.IteratedConstitutivePersistence

/-- Exact free-to-concrete occurrence transport already present in the model. -/
def freeToConcreteTransport
    {P : CircularPresentation}
    (A : ConcreteContinuationAlgebra P)
    {source target : PositiveConstitution P}
    (history : GeneratedHistory source target) :
    ExactTypeTransport
      (History.Occurrence history)
      (History.Occurrence (A.realizeHistory history)) :=
  ConstitutivePersistence.interpretationTransport
    (exactlyInterpretHistory A history)

/--
Concrete interpretation preserves the constructor-generated chronology
pointwise.
-/
theorem concreteForwardOccurrence_preserves_precedesBool
    {P : CircularPresentation}
    (A : ConcreteContinuationAlgebra P)
    {source target : PositiveConstitution P}
    (history : GeneratedHistory source target)
    (first second : History.Occurrence history) :
    occurrencePrecedesBool
        (concreteForwardOccurrence A history first)
        (concreteForwardOccurrence A history second) =
      occurrencePrecedesBool first second := by
  induction history with
  | root =>
      exact nomatch first
  | extend previous step inductionHypothesis =>
      cases step.formedByFreeLayer
      cases first with
      | last =>
          cases second <;> rfl
      | earlier firstPrevious =>
          cases second with
          | last =>
              rfl
          | earlier secondPrevious =>
              exact inductionHypothesis firstPrevious secondPrevious

/-- Backward concrete interpretation preserves the same derived chronology. -/
theorem concreteBackwardOccurrence_preserves_precedesBool
    {P : CircularPresentation}
    (A : ConcreteContinuationAlgebra P)
    {source target : PositiveConstitution P}
    (history : GeneratedHistory source target)
    (first second :
      History.Occurrence (A.realizeHistory history)) :
    occurrencePrecedesBool
        (concreteBackwardOccurrence A history first)
        (concreteBackwardOccurrence A history second) =
      occurrencePrecedesBool first second := by
  calc
    occurrencePrecedesBool
        (concreteBackwardOccurrence A history first)
        (concreteBackwardOccurrence A history second) =
      occurrencePrecedesBool
        (concreteForwardOccurrence A history
          (concreteBackwardOccurrence A history first))
        (concreteForwardOccurrence A history
          (concreteBackwardOccurrence A history second)) :=
      (concreteForwardOccurrence_preserves_precedesBool
        A history
        (concreteBackwardOccurrence A history first)
        (concreteBackwardOccurrence A history second)).symm
    _ = occurrencePrecedesBool first second := by
      rw [concreteForwardBackward A history first,
        concreteForwardBackward A history second]

/-- The exact interpretation is an intrinsic alignment derived from the histories. -/
def freeToConcreteAlignment
    {P : CircularPresentation}
    (A : ConcreteContinuationAlgebra P)
    {source target : PositiveConstitution P}
    (history : GeneratedHistory source target) :
    IndependentCompatibleExactAlignment
      (HistoryDerivedAlignment.context
        history (A.realizeHistory history)) :=
  { transport := freeToConcreteTransport A history
    preservesPattern := by
      intro first second third fourth
      constructor
      · intro sourceEquality
        have sourceBool :=
          (historyRelation_eq_iff_bool_eq
            first second third fourth).mp sourceEquality
        apply
          (historyRelation_eq_iff_bool_eq
            (concreteForwardOccurrence A history first)
            (concreteForwardOccurrence A history second)
            (concreteForwardOccurrence A history third)
            (concreteForwardOccurrence A history fourth)).mpr
        calc
          occurrencePrecedesBool
              (concreteForwardOccurrence A history first)
              (concreteForwardOccurrence A history second) =
            occurrencePrecedesBool first second :=
              concreteForwardOccurrence_preserves_precedesBool
                A history first second
          _ = occurrencePrecedesBool third fourth := sourceBool
          _ = occurrencePrecedesBool
              (concreteForwardOccurrence A history third)
              (concreteForwardOccurrence A history fourth) :=
                (concreteForwardOccurrence_preserves_precedesBool
                  A history third fourth).symm
      · intro targetEquality
        have targetBool :=
          (historyRelation_eq_iff_bool_eq
            (concreteForwardOccurrence A history first)
            (concreteForwardOccurrence A history second)
            (concreteForwardOccurrence A history third)
            (concreteForwardOccurrence A history fourth)).mp
              targetEquality
        apply
          (historyRelation_eq_iff_bool_eq
            first second third fourth).mpr
        calc
          occurrencePrecedesBool first second =
            occurrencePrecedesBool
              (concreteForwardOccurrence A history first)
              (concreteForwardOccurrence A history second) :=
                (concreteForwardOccurrence_preserves_precedesBool
                  A history first second).symm
          _ = occurrencePrecedesBool
              (concreteForwardOccurrence A history third)
              (concreteForwardOccurrence A history fourth) := targetBool
          _ = occurrencePrecedesBool third fourth :=
              concreteForwardOccurrence_preserves_precedesBool
                A history third fourth }

/-- Closed free-to-concrete constitutive alignment. -/
def freeToConcreteConstitutiveAlignment
    {P : CircularPresentation}
    (A : ConcreteContinuationAlgebra P)
    {source target : PositiveConstitution P}
    (history : GeneratedHistory source target) :
    HistoryDerivedAlignment.ConstitutiveAlignment
      history (A.realizeHistory history) :=
  ⟨freeToConcreteAlignment A history⟩

/-- Existing exact transport between two concrete realizations of one free history. -/
def concreteToConcreteTransport
    {P : CircularPresentation}
    (A B : ConcreteContinuationAlgebra P)
    {source target : PositiveConstitution P}
    (history : GeneratedHistory source target) :
    ExactTypeTransport
      (History.Occurrence (A.realizeHistory history))
      (History.Occurrence (B.realizeHistory history)) :=
  (freeToConcreteTransport A history).reverse.compose
    (freeToConcreteTransport B history)

/--
The existing concrete-to-concrete transport is intrinsically compatible with
the chronology derived independently on each concrete history.
-/
def concreteToConcreteAlignment
    {P : CircularPresentation}
    (A B : ConcreteContinuationAlgebra P)
    {source target : PositiveConstitution P}
    (history : GeneratedHistory source target) :
    IndependentCompatibleExactAlignment
      (HistoryDerivedAlignment.context
        (A.realizeHistory history)
        (B.realizeHistory history)) :=
  { transport := concreteToConcreteTransport A B history
    preservesPattern := by
      intro first second third fourth
      constructor
      · intro sourceEquality
        have sourceBool :=
          (historyRelation_eq_iff_bool_eq
            first second third fourth).mp sourceEquality
        apply
          (historyRelation_eq_iff_bool_eq
            ((concreteToConcreteTransport A B history).forward first)
            ((concreteToConcreteTransport A B history).forward second)
            ((concreteToConcreteTransport A B history).forward third)
            ((concreteToConcreteTransport A B history).forward fourth)).mpr
        change
          occurrencePrecedesBool
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history first))
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history second)) =
            occurrencePrecedesBool
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history third))
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history fourth))
        calc
          occurrencePrecedesBool
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history first))
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history second)) =
            occurrencePrecedesBool
              (concreteBackwardOccurrence A history first)
              (concreteBackwardOccurrence A history second) :=
                concreteForwardOccurrence_preserves_precedesBool
                  B history _ _
          _ = occurrencePrecedesBool first second :=
                concreteBackwardOccurrence_preserves_precedesBool
                  A history first second
          _ = occurrencePrecedesBool third fourth := sourceBool
          _ = occurrencePrecedesBool
              (concreteBackwardOccurrence A history third)
              (concreteBackwardOccurrence A history fourth) :=
                (concreteBackwardOccurrence_preserves_precedesBool
                  A history third fourth).symm
          _ = occurrencePrecedesBool
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history third))
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history fourth)) :=
                (concreteForwardOccurrence_preserves_precedesBool
                  B history _ _).symm
      · intro targetEquality
        have targetBool :=
          (historyRelation_eq_iff_bool_eq
            ((concreteToConcreteTransport A B history).forward first)
            ((concreteToConcreteTransport A B history).forward second)
            ((concreteToConcreteTransport A B history).forward third)
            ((concreteToConcreteTransport A B history).forward fourth)).mp
              targetEquality
        apply
          (historyRelation_eq_iff_bool_eq
            first second third fourth).mpr
        change
          occurrencePrecedesBool
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history first))
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history second)) =
            occurrencePrecedesBool
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history third))
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history fourth))
          at targetBool
        calc
          occurrencePrecedesBool first second =
            occurrencePrecedesBool
              (concreteBackwardOccurrence A history first)
              (concreteBackwardOccurrence A history second) :=
                (concreteBackwardOccurrence_preserves_precedesBool
                  A history first second).symm
          _ = occurrencePrecedesBool
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history first))
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history second)) :=
                (concreteForwardOccurrence_preserves_precedesBool
                  B history _ _).symm
          _ = occurrencePrecedesBool
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history third))
              (concreteForwardOccurrence B history
                (concreteBackwardOccurrence A history fourth)) := targetBool
          _ = occurrencePrecedesBool
              (concreteBackwardOccurrence A history third)
              (concreteBackwardOccurrence A history fourth) :=
                concreteForwardOccurrence_preserves_precedesBool
                  B history _ _
          _ = occurrencePrecedesBool third fourth :=
                concreteBackwardOccurrence_preserves_precedesBool
                  A history third fourth }

/-- Closed concrete-to-concrete constitutive alignment. -/
def concreteToConcreteConstitutiveAlignment
    {P : CircularPresentation}
    (A B : ConcreteContinuationAlgebra P)
    {source target : PositiveConstitution P}
    (history : GeneratedHistory source target) :
    HistoryDerivedAlignment.ConstitutiveAlignment
      (A.realizeHistory history)
      (B.realizeHistory history) :=
  ⟨concreteToConcreteAlignment A B history⟩

/--
Any history-derived compatible alignment between two concrete realizations is
forced to agree with the already existing exact realization transport.
-/
theorem concreteToConcrete_is_canonical
    {P : CircularPresentation}
    (A B : ConcreteContinuationAlgebra P)
    {source target : PositiveConstitution P}
    (history : GeneratedHistory source target)
    (candidate :
      HistoryDerivedAlignment.ConstitutiveAlignment
        (A.realizeHistory history)
        (B.realizeHistory history))
    (occurrence :
      History.Occurrence (A.realizeHistory history)) :
    candidate.initial.transport.forward occurrence =
      (concreteToConcreteTransport A B history).forward occurrence :=
  HistoryDerivedAlignment.constitutiveAlignment_forward_unique
    (A.realizeHistory history)
    (B.realizeHistory history)
    candidate
    (concreteToConcreteConstitutiveAlignment A B history)
    occurrence

/-- Circular arbitrary-depth specialization of the intrinsic concrete alignment. -/
def iteratedConcreteConstitutiveAlignment
    (P : CircularPresentation)
    (A B : ConcreteContinuationAlgebra P)
    (depth : Nat) :
    HistoryDerivedAlignment.ConstitutiveAlignment
      (A.realizeHistory (iteratedHistory P depth).history)
      (B.realizeHistory (iteratedHistory P depth).history) :=
  concreteToConcreteConstitutiveAlignment
    A B (iteratedHistory P depth).history

/--
The history-derived canonical transport is pointwise the transport already used
by finite constitutive persistence.
-/
theorem iteratedConcreteAlignment_forward_eq_realizationTransport
    (P : CircularPresentation)
    (A B : ConcreteContinuationAlgebra P)
    (depth : Nat)
    (occurrence :
      (iteratedRealization P A depth).Concrete) :
    (iteratedConcreteConstitutiveAlignment P A B depth).initial.transport.forward
        occurrence =
      ((iteratedRealization P A depth).transport
        (iteratedRealization P B depth)).forward occurrence := by
  change
    (exactlyInterpretHistory B (iteratedHistory P depth).history).forwardOccurrence
        ((exactlyInterpretHistory A
          (iteratedHistory P depth).history).backwardOccurrence occurrence) =
      (exactlyInterpretHistory B
        (iteratedHistory P depth).history).forwardOccurrence
        ((iteratedOccurrenceSpoke P depth).forward
          ((iteratedOccurrenceSpoke P depth).backward
            ((exactlyInterpretHistory A
              (iteratedHistory P depth).history).backwardOccurrence occurrence)))
  rw [(iteratedOccurrenceSpoke P depth).backwardForward]

/--
Consequently every compatible history-derived alignment of the two concrete
circular realizations agrees with the established persistence transport.
-/
theorem iteratedConcreteAlignment_canonical
    (P : CircularPresentation)
    (A B : ConcreteContinuationAlgebra P)
    (depth : Nat)
    (candidate :
      HistoryDerivedAlignment.ConstitutiveAlignment
        (A.realizeHistory (iteratedHistory P depth).history)
        (B.realizeHistory (iteratedHistory P depth).history))
    (occurrence :
      (iteratedRealization P A depth).Concrete) :
    candidate.initial.transport.forward occurrence =
      ((iteratedRealization P A depth).transport
        (iteratedRealization P B depth)).forward occurrence := by
  have firstAgreement :
      candidate.initial.transport.forward occurrence =
        (concreteToConcreteTransport
          A B (iteratedHistory P depth).history).forward occurrence :=
    concreteToConcrete_is_canonical
      A B (iteratedHistory P depth).history candidate occurrence
  have secondAgreement :
      (concreteToConcreteTransport
        A B (iteratedHistory P depth).history).forward occurrence =
        ((iteratedRealization P A depth).transport
          (iteratedRealization P B depth)).forward occurrence := by
    exact
      iteratedConcreteAlignment_forward_eq_realizationTransport
        P A B depth occurrence
  exact firstAgreement.trans secondAgreement

end HistoryDerivedIntrinsicAlignment
end StrongPerimetralTurning

/- AXIOM_AUDIT_BEGIN -/
#print axioms StrongPerimetralTurning.HistoryDerivedIntrinsicAlignment.freeToConcreteTransport
#print axioms StrongPerimetralTurning.HistoryDerivedIntrinsicAlignment.concreteForwardOccurrence_preserves_precedesBool
#print axioms StrongPerimetralTurning.HistoryDerivedIntrinsicAlignment.concreteBackwardOccurrence_preserves_precedesBool
#print axioms StrongPerimetralTurning.HistoryDerivedIntrinsicAlignment.freeToConcreteAlignment
#print axioms StrongPerimetralTurning.HistoryDerivedIntrinsicAlignment.freeToConcreteConstitutiveAlignment
#print axioms StrongPerimetralTurning.HistoryDerivedIntrinsicAlignment.concreteToConcreteTransport
#print axioms StrongPerimetralTurning.HistoryDerivedIntrinsicAlignment.concreteToConcreteAlignment
#print axioms StrongPerimetralTurning.HistoryDerivedIntrinsicAlignment.concreteToConcreteConstitutiveAlignment
#print axioms StrongPerimetralTurning.HistoryDerivedIntrinsicAlignment.concreteToConcrete_is_canonical
#print axioms StrongPerimetralTurning.HistoryDerivedIntrinsicAlignment.iteratedConcreteConstitutiveAlignment
#print axioms StrongPerimetralTurning.HistoryDerivedIntrinsicAlignment.iteratedConcreteAlignment_forward_eq_realizationTransport
#print axioms StrongPerimetralTurning.HistoryDerivedIntrinsicAlignment.iteratedConcreteAlignment_canonical
/- AXIOM_AUDIT_END -/
